name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: renderinc/render-deploy-action@v1
        with:
          service_name: barvback
          dockerfile_path: target/barvBackEnd-1.0-SNAPSHOT.jar
